"""Every tested change against its own reference: the feature-test ledger.

    python -m rentfrontier.ledger --out ../docs/model/feature-tests.md

A test is a pair of PSIS-LOO records that differ by one change, on the same
dataset, rows, commit and run settings (the rest of the run name):

- **A feature set.** The test run's feature set names its `base` set
  (`features.FEATURE_SETS`), and a run named the same with the base set in its
  place exists: `m7-…-nb3-lines-v1-rows-e4c16ae-…` against
  `m7-…-nb3-coded-v2-rows-e4c16ae-…`.
- **A model term.** The test run's model is the reference's with one more
  term: `m7-…-bedtime-yearnoise` against `m7-…-bedtime`.

Each row gives the paired difference on the rows both keep
(`leaderboard.paired_loo`), its SE combined with the Monte Carlo error as the
selection rules do (`leaderboard.tie_tolerance`), and a verdict: a gain or a
loss beyond two of those SEs, else no clear gain. What each change is comes
from docs/model/feature-tests.json.

Ben, 2026-10-06: tests that did not win are revisited when the dataset changes,
location features first (adding neighbourhoods widens their range). A row is
marked for a retest when its run's dataset is not the current one
(`data.DATASET`).
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from . import data, features, leaderboard

REPO = Path(__file__).resolve().parents[3]
NOTES = REPO / "docs" / "model" / "feature-tests.json"


def base_set(feature_set: str) -> str | None:
    fn = features.FEATURE_SETS.get(feature_set)
    return getattr(fn, "keywords", {}).get("base")


def pairs(loo: dict):
    """(change, test record, reference record) for every one-change pair."""
    for name, r in loo.items():
        fs, model = r.get("feature_set"), r.get("model")
        base = base_set(fs) if fs else None
        if base and f"-{fs}-" in name:
            ref = name.replace(f"-{fs}-", f"-{base}-", 1)
            if ref in loo:
                yield fs, r, loo[ref]
        if model and name.startswith(model + "-"):
            rest, terms = name[len(model) :], model.split("-")
            for i in range(1, len(terms)):
                ref = "-".join(terms[:i] + terms[i + 1 :]) + rest
                if ref in loo:
                    yield "+" + terms[i], r, loo[ref]


def run_record(name: str) -> dict:
    path = leaderboard.RUNS / name / "result.json"
    return json.loads(path.read_text()) if path.exists() else {}


def verdict(diff: float, se: float) -> str:
    if diff > 2 * se:
        return "gain"
    if diff < -2 * se:
        return "worse"
    return "no clear gain"


def rows(loo: dict, notes: dict, current: str, paired=leaderboard.paired_loo):
    out = []
    for change, test, ref in pairs(loo):
        try:
            diff, se, mcse = paired(test["_dir"], ref["_dir"])
        except ValueError:  # rows differ beyond the data rules: not one change
            continue
        se = leaderboard.tie_tolerance(se, mcse) / 2
        run = run_record(test["source_run"])
        dataset = Path(run.get("dataset", "")).name
        note = notes.get(change, {})
        v = verdict(diff, se)
        if change in features.READS_EARLIER_RENTS:
            v = "PSIS-LOO leaks; judged on the latest split"
        retest = ""
        if v == "no clear gain" or v == "worse":
            location = note.get("kind") == "location"
            if dataset and dataset != current:
                retest = "due, location" if location else "due"
            elif location:
                retest = "next neighbourhood"
        out.append(
            {
                "date": run.get("started_at", "")[:10],
                "change": change,
                "about": note.get("about", ""),
                "kind": note.get("kind", ""),
                "pr": note.get("pr"),
                "dataset": dataset,
                "rows": test.get("rows"),
                "diff": diff,
                "se": se,
                "verdict": v,
                "retest": retest,
                "test": test["source_run"],
                "reference": ref["source_run"],
            }
        )
    return sorted(out, key=lambda r: (r["date"], r["test"]), reverse=True)


def markdown(entries: list[dict], current: str) -> str:
    lines = [
        "# Feature and model tests",
        "",
        "Generated by `python -m rentfrontier.ledger --out ../docs/model/feature-tests.md`"
        " (run from `frontier/`); what each change is lives in `feature-tests.json`.",
        "Every pair of PSIS-LOO records that differ by one feature set or one model term,"
        " paired on the rows both keep. ± is the paired SE combined with Monte Carlo"
        " error; a gain or loss needs more than 2 of them.",
        "",
        f"Retest: a test without a clear gain is **due** when it ran on another dataset than"
        f" the current one (`{current}`). Location features (kind `location`) are retested"
        " first when a neighbourhood is added, since more neighbourhoods widen their range"
        " (Ben, 2026-10-06).",
        "",
        "| Date | Change | What | Kind | ΔPSIS-LOO | Verdict | Retest | Dataset (rows) | PR | Test run | Reference run |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for e in entries:
        pr = f"#{e['pr']}" if e["pr"] else ""
        lines.append(
            f"| {e['date']} | `{e['change']}` | {e['about']} | {e['kind']} "
            f"| {e['diff']:+,.1f} ± {e['se']:,.1f} | {e['verdict']} | {e['retest']} "
            f"| {e['dataset']} ({e['rows']:,}) | {pr} | `{e['test']}` | `{e['reference']}` |"
        )
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--out", type=Path, help="write the markdown ledger here")
    args = parser.parse_args()
    notes = json.loads(NOTES.read_text())["changes"] if NOTES.exists() else {}
    current = data.DATASET.name
    text = markdown(rows(leaderboard.load_loo(), notes, current), current)
    if args.out:
        args.out.write_text(text)
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
